

const destination = [
  {
    id: 1,
    name: "Kedarnath",
    image: "/images/kedarnath.jpg",
    description: "One of the holiest Hindu temples dedicated to Lord Shiva",
    bestTime: "May to June, September to October",
    weather: "Cold",
    altitude: "3,583 m",
    category: "Pilgrimage",
  },
  {
    id: 2,
    name: "Rishikesh",
    image: "/images/rishikesh.avif",
    description: "World Capital of Yoga and Adventure Sports Hub",
    bestTime: "September to April",
    weather: "Moderate",
    altitude: "372 m",
    category: "Adventure",
  },
  {
    id: 3,
    name: "Mussoorie",
    image: "/images/mussoorie.png",
    description: "Queen of Hills with panoramic Himalayan views",
    bestTime: "March to June, September to November",
    weather: "Pleasant",
    altitude: "2,005 m",
    category: "Hill Station",
  },
  {
    id: 4,
    name: "Nainital",
    image: "/images/nainital.png",
    description: "Famous lake city surrounded by mountains",
    bestTime: "March to June, September to November",
    weather: "Pleasant",
    altitude: "2,084 m",
    category: "Hill Station",
  },
  {
    id: 5,
    name: "Badrinath",
    image: "/images/badrinath.jpg",
    description: "Sacred temple town and part of Char Dham",
    bestTime: "May to June, September to October",
    weather: "Cold",
    altitude: "3,300 m",
    category: "Pilgrimage",
  },
  {
    id: 6,
    name: "Valley of Flowers",
    image: "/images/valley_of_flower.avif",
    description:
      "UNESCO World Heritage Site known for its meadows of endemic alpine flowers",
    bestTime: "July to September",
    weather: "Cool",
    altitude: "3,658 m",
    category: "Nature",
  },
  {
    id: 7,
    name: "Auli",
    image: "/images/auli.jpg",
    description: "Popular skiing destination with beautiful slopes",
    bestTime: "November to March",
    weather: "Cold",
    altitude: "2,800 m",
    category: "Adventure",
  },
  {
    id: 8,
    name: "Jim Corbett",
    image: "/images/national_park.jpg",
    description: "Famous national park known for tigers and wildlife",
    bestTime: "November to June",
    weather: "Moderate",
    altitude: "1,220 m",
    category: "Wildlife",
  },
];

export default destination;
